### ISSUE TITLE
Can not install the lib

### ISSUE THREAD

**Issue by JimTR** [ipdata/php#4]
Hi
trying to get composer to install the code the response from composer is : 
<b>Could not find a version of package ipdata/api-client matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability</b>
using : 
PHP 7.4
however I can not get a response from the following code which I would prefer to use
`
$ch = curl_init();
	     curl_setopt($ch, CURLOPT_URL, ' https://api.ipdata.co?api-key=key');
	     curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	$xm = curl_exec($ch);
		curl_close($ch);
`
but this works
`
$xm =shell_exec('curl -s  https://api.ipdata.co?api-key=key');
`
any reason ?

**Comment by jonathan-kosgei** [comment]
You might need to install curl for php, see https://stackoverflow.com/a/6382581/3176550

**Comment by JimTR** [comment]
it was a typo in the command notice the white space in the curl command

**Comment by jonathan-kosgei** [comment]
Glad you caught it!

**Comment by jonathan-kosgei** [comment]
@JimTR Are you still unable to import the library?

**Comment by Nyholm** [comment]
I see that the repository is moved. 

I've added a tag and sent a request to `ipdata` owners to allow the Github Packagist application to have read permissions. This will make sure the package is automatically updated.

**Comment by JimTR** [comment]
Ok I'll try again at a later date and yes I can not install the code. So I did a quick class which will perhaps do the same thing.
