### ISSUE TITLE
php 8

### ISSUE THREAD

**Issue by madsem** [ipdata/php#5]
Hey there,

trying to upgrade everything to php 8, but ipdata package is locked to 7.
Can you make this happen? :)

**Comment by andreas-o44** [comment]
I second that, please support php8. thank you

**Comment by atiweb** [comment]
The base code work on PHP8, just remove from composer, then update, then add manually dependencies on project and its working now. But its much easier no doubt to add support to the project. 
Here how to activate again after remove from composer:
First, backup all, then:
In vendor/composer/autolad_static.php add:
'I' => 
        array (
            'Ipdata\\ApiClient\\' => 17,
        ),

//  more ahead:      
                'Ipdata\\ApiClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/ipdata/api-client/src',
        ),
In vendor/composer/autolad_psr4.php add:
'Ipdata\\ApiClient\\' => array($vendorDir . '/ipdata/api-client/src'),

just compare both version of files before and after composer update or after install support to php 8 in your project
It may be needed to update other files depending of the project type and framework used.

**Comment by Nyholm** [comment]
PHP 8 support was added in #6. 

Expect a new release soon.
